// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using UnityEngine;


public partial class SteamVR_Input
{
    
    public static SteamVR_Input_ActionSet_default _default;
    
    public static void Dynamic_InitializeActionSets()
    {
        SteamVR_Input._default.Initialize();
        SteamVR_Input.Dynamic_InitializeInstanceActionSets();
    }
    
    public static void Dynamic_InitializeInstanceActionSets()
    {
        SteamVR_Input._default = ((SteamVR_Input_ActionSet_default)(SteamVR_Input_References.GetActionSet("_default")));
        SteamVR_Input.actionSets = new SteamVR_Input_ActionSet[]
        {
                SteamVR_Input._default};
    }
}
