// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using UnityEngine;


public partial class SteamVR_Input
{
    
    public static SteamVR_Input_Action_Vector2 __actions_default_in_Move;
    
    public static SteamVR_Input_Action_Boolean __actions_default_in_Use;
    
    public static SteamVR_Input_Action_Boolean __actions_default_in_InteractUI;
    
    public static SteamVR_Input_Action_Boolean __actions_default_in_Teleport;
    
    public static SteamVR_Input_Action_Boolean __actions_default_in_GrabPinch;
    
    public static SteamVR_Input_Action_Boolean __actions_default_in_GrabGrip;
    
    public static SteamVR_Input_Action_Pose __actions_default_in_Pose;
    
    public static SteamVR_Input_Action_Skeleton __actions_default_in_SkeletonLeftHand;
    
    public static SteamVR_Input_Action_Skeleton __actions_default_in_SkeletonRightHand;
    
    public static SteamVR_Input_Action_Vibration __actions_default_out_Haptic;
    
    public static void Dynamic_InitializeActions()
    {
        SteamVR_Input.__actions_default_in_Move.Initialize();
        SteamVR_Input.__actions_default_in_Use.Initialize();
        SteamVR_Input.__actions_default_in_InteractUI.Initialize();
        SteamVR_Input.__actions_default_in_Teleport.Initialize();
        SteamVR_Input.__actions_default_in_GrabPinch.Initialize();
        SteamVR_Input.__actions_default_in_GrabGrip.Initialize();
        SteamVR_Input.__actions_default_in_Pose.Initialize();
        SteamVR_Input.__actions_default_in_SkeletonLeftHand.Initialize();
        SteamVR_Input.__actions_default_in_SkeletonRightHand.Initialize();
        SteamVR_Input.__actions_default_out_Haptic.Initialize();
    }
    
    public static void Dynamic_InitializeInstanceActions()
    {
        SteamVR_Input.__actions_default_in_Move = ((SteamVR_Input_Action_Vector2)(SteamVR_Input_References.GetAction("__actions_default_in_Move")));
        SteamVR_Input.__actions_default_in_Use = ((SteamVR_Input_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_Use")));
        SteamVR_Input.__actions_default_in_InteractUI = ((SteamVR_Input_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_InteractUI")));
        SteamVR_Input.__actions_default_in_Teleport = ((SteamVR_Input_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_Teleport")));
        SteamVR_Input.__actions_default_in_GrabPinch = ((SteamVR_Input_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_GrabPinch")));
        SteamVR_Input.__actions_default_in_GrabGrip = ((SteamVR_Input_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_GrabGrip")));
        SteamVR_Input.__actions_default_in_Pose = ((SteamVR_Input_Action_Pose)(SteamVR_Input_References.GetAction("__actions_default_in_Pose")));
        SteamVR_Input.__actions_default_in_SkeletonLeftHand = ((SteamVR_Input_Action_Skeleton)(SteamVR_Input_References.GetAction("__actions_default_in_SkeletonLeftHand")));
        SteamVR_Input.__actions_default_in_SkeletonRightHand = ((SteamVR_Input_Action_Skeleton)(SteamVR_Input_References.GetAction("__actions_default_in_SkeletonRightHand")));
        SteamVR_Input.__actions_default_out_Haptic = ((SteamVR_Input_Action_Vibration)(SteamVR_Input_References.GetAction("__actions_default_out_Haptic")));
        SteamVR_Input.actions = new SteamVR_Input_Action[]
        {
                SteamVR_Input.__actions_default_in_Move,
                SteamVR_Input.__actions_default_in_Use,
                SteamVR_Input.__actions_default_in_InteractUI,
                SteamVR_Input.__actions_default_in_Teleport,
                SteamVR_Input.__actions_default_in_GrabPinch,
                SteamVR_Input.__actions_default_in_GrabGrip,
                SteamVR_Input.__actions_default_in_Pose,
                SteamVR_Input.__actions_default_in_SkeletonLeftHand,
                SteamVR_Input.__actions_default_in_SkeletonRightHand,
                SteamVR_Input.__actions_default_out_Haptic};
        SteamVR_Input.actionsIn = new SteamVR_Input_Action_In[]
        {
                SteamVR_Input.__actions_default_in_Move,
                SteamVR_Input.__actions_default_in_Use,
                SteamVR_Input.__actions_default_in_InteractUI,
                SteamVR_Input.__actions_default_in_Teleport,
                SteamVR_Input.__actions_default_in_GrabPinch,
                SteamVR_Input.__actions_default_in_GrabGrip,
                SteamVR_Input.__actions_default_in_Pose,
                SteamVR_Input.__actions_default_in_SkeletonLeftHand,
                SteamVR_Input.__actions_default_in_SkeletonRightHand};
        SteamVR_Input.actionsOut = new SteamVR_Input_Action_Out[]
        {
                SteamVR_Input.__actions_default_out_Haptic};
        SteamVR_Input.actionsVibration = new SteamVR_Input_Action_Vibration[]
        {
                SteamVR_Input.__actions_default_out_Haptic};
        SteamVR_Input.actionsPose = new SteamVR_Input_Action_Pose[]
        {
                SteamVR_Input.__actions_default_in_Pose};
        SteamVR_Input.actionsBoolean = new SteamVR_Input_Action_Boolean[]
        {
                SteamVR_Input.__actions_default_in_Use,
                SteamVR_Input.__actions_default_in_InteractUI,
                SteamVR_Input.__actions_default_in_Teleport,
                SteamVR_Input.__actions_default_in_GrabPinch,
                SteamVR_Input.__actions_default_in_GrabGrip};
        SteamVR_Input.actionsSingle = new SteamVR_Input_Action_Single[0];
        SteamVR_Input.actionsVector2 = new SteamVR_Input_Action_Vector2[]
        {
                SteamVR_Input.__actions_default_in_Move};
        SteamVR_Input.actionsVector3 = new SteamVR_Input_Action_Vector3[0];
        SteamVR_Input.actionsSkeleton = new SteamVR_Input_Action_Skeleton[]
        {
                SteamVR_Input.__actions_default_in_SkeletonLeftHand,
                SteamVR_Input.__actions_default_in_SkeletonRightHand};
        SteamVR_Input.actionsNonPoseNonSkeletonIn = new SteamVR_Input_Action_In[]
        {
                SteamVR_Input.__actions_default_in_Move,
                SteamVR_Input.__actions_default_in_Use,
                SteamVR_Input.__actions_default_in_InteractUI,
                SteamVR_Input.__actions_default_in_Teleport,
                SteamVR_Input.__actions_default_in_GrabPinch,
                SteamVR_Input.__actions_default_in_GrabGrip};
    }
}
