// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using UnityEngine;


public class SteamVR_Input_ActionSet_default : SteamVR_Input_ActionSet
{
    
    public static SteamVR_Input_ActionSet_default_In inActions;
    
    public static SteamVR_Input_ActionSet_default_Out outActions;
}
