// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using UnityEngine;


public class SteamVR_Input_ActionSet_default_In : SteamVR_Input_Action_List
{
    
    public static SteamVR_Input_Action_Vector2 Move;
    
    public static SteamVR_Input_Action_Boolean Use;
    
    public static SteamVR_Input_Action_Boolean InteractUI;
    
    public static SteamVR_Input_Action_Boolean Teleport;
    
    public static SteamVR_Input_Action_Boolean GrabPinch;
    
    public static SteamVR_Input_Action_Boolean GrabGrip;
    
    public static SteamVR_Input_Action_Pose Pose;
    
    public static SteamVR_Input_Action_Skeleton SkeletonLeftHand;
    
    public static SteamVR_Input_Action_Skeleton SkeletonRightHand;
}
